variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

stages:
  - run_danger

before_script:
  - flutter doctor -v
  - flutter clean

  # generate code & multi-lang var intl & image constant
  - sh run.sh

  # test
  # - flutter test
  
run_danger:
  stage: run_danger
  variables:
    DANGER_GITLAB_HOST: devops.runsystem.info
    DANGER_GITLAB_API_BASE_URL: https://devops.runsystem.info/api/v4
    DANGER_GITLAB_API_TOKEN: "zrWqugP6oQ_MRMaChV9V"
    CI_JOB_TOKEN: "zrWqugP6oQ_MRMaChV9V"
  script:
    - flutter analyze > flutter_analyze_report.txt || true
    - bundle exec danger
  artifacts:
    paths:
      - flutter_analyze_report.txt
  only:
    - merge_requests